# shellcheck shell=bash
# lib/official-dls.sh — stand up the OFFICIAL NVIDIA DLS 3.6.1 appliance locally
# from a downloaded nls-3.6.1-bios distribution.
#
# IMPORTANT: these are NVIDIA's proprietary images, loaded from the tarballs you
# downloaded under your own entitlement. They are NEVER pushed anywhere. This path
# licenses R570/R580/R595 guests natively — no gridd-unlock-patcher required.
#
# The server stand-up is automated here; binding licenses (NVIDIA Licensing Portal
# registration + client-token download from the DLS admin console) is manual — see
# _print_official_dls_next_steps and docs/OFFICIAL_DLS.md.

OFFICIAL_DLS_PROJECT="nvidia-dls"
OFFICIAL_DLS_APPLIANCE_IMAGE="dls:appliance_3.6.1"
OFFICIAL_DLS_PGSQL_IMAGE="dls:pgsql_3.6.1"

# Locate the nls-3.6.1-bios distribution directory.
_find_nls_dir() {
    local d
    for d in "${NLS_DIR:-}" ./nls-3.6.1-bios /root/nls-3.6.1-bios /opt/nls-3.6.1-bios "$HOME/nls-3.6.1-bios"; do
        [ -n "$d" ] || continue
        if [ -f "$d/docker/docker-compose.yml" ]; then echo "$d"; return 0; fi
    done
    return 1
}

# docker load each image from its tarball, unless already present.
_load_official_images() {
    local nls="$1" img tar
    for img_tar in \
        "${OFFICIAL_DLS_APPLIANCE_IMAGE}=dls_appliance_3.6.1.tar.gz" \
        "${OFFICIAL_DLS_PGSQL_IMAGE}=dls_pgsql_3.6.1.tar.gz"; do
        img="${img_tar%%=*}"; tar="${img_tar#*=}"
        if docker image inspect "$img" >/dev/null 2>&1; then
            log_info "Image already loaded: $img"
            continue
        fi
        [ -f "$nls/$tar" ] || die "Missing image tarball: $nls/$tar"
        run_shell "Loading $img from $tar (large, please wait)" info \
            "gzip -dc '$nls/$tar' | docker load"
    done
}

# Warn if the chosen host ports are already published by another container.
_preflight_ports_official() {
    local p
    for p in "$@"; do
        local holder
        holder="$(docker ps --format '{{.Names}}\t{{.Ports}}' 2>/dev/null \
            | awk -v pat=":${p}->" 'index($0,pat){print $1}' | head -1)"
        if [ -n "$holder" ]; then
            log_warn "Port ${p} is already published by container '${holder}'."
            ask_yes_no "Continue anyway (the DLS stack will fail to bind ${p})?" n \
                || die "Free port ${p} or choose different exposed ports, then re-run."
        fi
    done
}

setup_official_dls() {
    echo ""
    log_step "Official NVIDIA DLS 3.6.1 — local setup (nothing is published)"
    need_cmd docker || die "Docker is required. Run the 'license' step first to install it, or install Docker manually."
    docker compose version >/dev/null 2>&1 || die "The 'docker compose' plugin is required."

    log_warn "The official DLS stack is heavy (~6 GB RAM, postgres + rabbitmq, ports 443/80/5671/8080-8085)."
    log_warn "Recommended placement: a dedicated VM/LXC, not the Proxmox host. Continue only if this host has the ports/RAM free."

    local nls; nls="$(_find_nls_dir || true)"
    [ -n "$nls" ] || nls="$(ask_value 'Path to the nls-3.6.1-bios directory' '/root/nls-3.6.1-bios')"
    local compose="$nls/docker/docker-compose.yml"
    [ -f "$compose" ] || die "NVIDIA compose not found at $compose (is the distribution extracted there?)"

    _load_official_images "$nls"

    # Required configuration (the only three vars NVIDIA's compose has no defaults for).
    local ip host fqdn https http
    ip="$(_detect_host_ip)"
    host="$(hostname -s 2>/dev/null || echo dls)"
    fqdn="$(ask_value 'FQDN for the DLS (guests must be able to reach this)' "$(hostname -f 2>/dev/null || echo "$host")")"
    log_warn "Pick exposed ports that are free on this host (Proxmox web is 8006; our FastAPI-DLS, if used, is on 8443)."
    https="$(ask_value 'Exposed HTTPS port for the DLS' '443')"
    http="$(ask_value 'Exposed HTTP port for the DLS' '80')"

    cat >"$nls/docker/.env" <<EOF
# Generated by proxmox-vgpu-installer for the official NVIDIA DLS 3.6.1 stack.
DLS_PUBLIC_IP=$ip
FQDN=$fqdn
DLS_PRIVATE_HOSTNAME=$host
DLS_EXPOSED_HTTPS_PORT=$https
DLS_EXPOSED_HTTP_PORT=$http
EOF
    log_info "Wrote $nls/docker/.env (DLS_PUBLIC_IP=$ip, FQDN=$fqdn, ports ${https}/${http})"

    _preflight_ports_official "$https" "$http"

    run_command "Starting official DLS 3.6.1 (compose)" info \
        docker compose --env-file "$nls/docker/.env" -p "$OFFICIAL_DLS_PROJECT" -f "$compose" up -d

    _write_official_guest_scripts "$ip" "$https"
    _print_official_dls_next_steps "$ip" "$https"
}

# Guest scripts for the official DLS: install a client token you download from the
# DLS admin console, then restart gridd. NO gridd-unlock-patcher (natively trusted).
_write_official_guest_scripts() {
    local ip="$1" https="$2" dir="$VGPU_DIR/licenses"
    mkdir -p "$dir"
    cat >"$dir/license_official_linux.sh" <<'EOF'
#!/bin/bash
# Official NVIDIA DLS licensing for a LINUX guest — no gridd-unlock-patcher needed.
# Usage: ./license_official_linux.sh /path/to/client_configuration_token_*.tok
# Get the .tok by downloading a "client configuration token" from your DLS admin console.
set -e
TOK="${1:?usage: license_official_linux.sh /path/to/client_configuration_token.tok}"
install -d /etc/nvidia/ClientConfigToken
install -m 0644 "$TOK" /etc/nvidia/ClientConfigToken/
systemctl restart nvidia-gridd 2>/dev/null || service nvidia-gridd restart
sleep 2; nvidia-smi -q | grep -i License
EOF
    cat >"$dir/license_official_windows.ps1" <<'EOF'
# Official NVIDIA DLS licensing for a WINDOWS guest — no patching needed.
# Usage: .\license_official_windows.ps1 -Token C:\path\client_configuration_token.tok
param([Parameter(Mandatory=$true)][string]$Token)
$dest = "C:\Program Files\NVIDIA Corporation\vGPU Licensing\ClientConfigToken"
New-Item -ItemType Directory -Force -Path $dest | Out-Null
Copy-Item -Force $Token $dest
Restart-Service NVDisplay.ContainerLocalSystem
& 'nvidia-smi' -q | Select-String 'License'
EOF
    chmod +x "$dir/license_official_linux.sh"
    log_info "Official-DLS guest scripts written to $dir (they install a token you download from the DLS console)."
}

_print_official_dls_next_steps() {
    local ip="$1" https="$2"
    echo ""
    log_step "Official DLS — remaining (manual) steps to bind licenses"
    log_info "1) DLS admin console:  https://${ip}:${https}   (set the admin password on first login)."
    log_info "2) In the NVIDIA Licensing Portal, create a license server and allocate your vGPU licenses."
    log_info "3) Register this DLS instance with the portal (download the DLS instance token, upload it in the console)."
    log_info "4) In the console, install the license server / bind the allocated features."
    log_info "5) Download a 'client configuration token' (.tok) from the console."
    log_info "6) In each guest, run licenses/license_official_linux.sh <that.tok> (or the .ps1 on Windows)."
    log_warn "No gridd-unlock-patcher is needed on this path — the official DLS is trusted by all driver branches (incl. R595)."
    log_info "Full click-path: NVIDIA DLS 3.6.1 User Guide — https://docs.nvidia.com/license-system/dls/3.6.1/"
    echo ""
    log_info "Manage the stack:  docker compose -p ${OFFICIAL_DLS_PROJECT} ps   |   ... logs -f   |   ... down"
}

module_init "official-dls.sh"
